In [1]:
import requests

#### 1. Start by performing a GET request on the url above and convert the response into a BeautifulSoup object.

In [3]:
URL = 'https://realpython.github.io/fake-jobs/'

response = requests.get(URL)

In [4]:
type(response)

requests.models.Response

In [5]:
response.status_code

200

In [6]:
from bs4 import BeautifulSoup as BS

In [7]:
soup = BS(response.text)

In [8]:
print(soup.prettify())

<!DOCTYPE html>
<html>
 <head>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <title>
   Fake Python
  </title>
  <link href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css" rel="stylesheet"/>
 </head>
 <body>
  <section class="section">
   <div class="container mb-5">
    <h1 class="title is-1">
     Fake Python
    </h1>
    <p class="subtitle is-3">
     Fake Jobs for Your Web Scraping Journey
    </p>
   </div>
   <div class="container">
    <div class="columns is-multiline" id="ResultsContainer">
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Senior Python Developer
          </h2>
          <h3 class="subtitle is-6 company">
           Payne, Roberts and Davis
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Stewartbury, AA
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/senior-python-developer-0.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Energy engineer
          </h2>
          <h3 class="subtitle is-6 company">
           Vasquez-Davidson
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Christopherville, AA
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/energy-engineer-1.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Legal executive
          </h2>
          <h3 class="subtitle is-6 company">
           Jackson, Chambers and Levy
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Port Ericaburgh, AA
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/legal-executive-2.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Fitness centre manager
          </h2>
          <h3 class="subtitle is-6 company">
           Savage-Bradley
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          East Seanview, AP
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/fitness-centre-manager-3.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Product manager
          </h2>
          <h3 class="subtitle is-6 company">
           Ramirez Inc
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          North Jamieview, AP
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/product-manager-4.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Medical technical officer
          </h2>
          <h3 class="subtitle is-6 company">
           Rogers-Yates
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Davidville, AP
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/medical-technical-officer-5.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Physiological scientist
          </h2>
          <h3 class="subtitle is-6 company">
           Kramer-Klein
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          South Christopher, AE
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/physiological-scientist-6.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Textile designer
          </h2>
          <h3 class="subtitle is-6 company">
           Meyers-Johnson
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Port Jonathan, AE
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/textile-designer-7.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Television floor manager
          </h2>
          <h3 class="subtitle is-6 company">
           Hughes-Williams
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Osbornetown, AE
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/television-floor-manager-8.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Waste management officer
          </h2>
          <h3 class="subtitle is-6 company">
           Jones, Williams and Villa
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Scotttown, AP
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/waste-management-officer-9.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Software Engineer (Python)
          </h2>
          <h3 class="subtitle is-6 company">
           Garcia PLC
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Ericberg, AE
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/software-engineer-python-10.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Interpreter
          </h2>
          <h3 class="subtitle is-6 company">
           Gregory and Sons
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Ramireztown, AE
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/interpreter-11.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Architect
          </h2>
          <h3 class="subtitle is-6 company">
           Clark, Garcia and Sosa
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Figueroaview, AA
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/architect-12.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Meteorologist
          </h2>
          <h3 class="subtitle is-6 company">
           Bush PLC
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Kelseystad, AA
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/meteorologist-13.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Audiological scientist
          </h2>
          <h3 class="subtitle is-6 company">
           Salazar-Meyers
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Williamsburgh, AE
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/audiological-scientist-14.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           English as a second language teacher
          </h2>
          <h3 class="subtitle is-6 company">
           Parker, Murphy and Brooks
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Mitchellburgh, AE
         </p>
         <p class="is-small has-text-grey">

### a. Use the .find method to find the tag containing the first job title ("Senior Python Developer"). Hint: can you find a tag type and/or a class that could be helpful for extracting this information? Extract the text from this title.

In [10]:
soup.find('h2').text

'Senior Python Developer'

### b. Now, use what you did for the first title, but extract the job title for all jobs on this page. Store the results in a list.

In [12]:
job_title = soup.find_all('h2')

In [13]:
job_titles_list = [x.text for x in job_title]

In [14]:
job_titles_list

['Senior Python Developer',
 'Energy engineer',
 'Legal executive',
 'Fitness centre manager',
 'Product manager',
 'Medical technical officer',
 'Physiological scientist',
 'Textile designer',
 'Television floor manager',
 'Waste management officer',
 'Software Engineer (Python)',
 'Interpreter',
 'Architect',
 'Meteorologist',
 'Audiological scientist',
 'English as a second language teacher',
 'Surgeon',
 'Equities trader',
 'Newspaper journalist',
 'Materials engineer',
 'Python Programmer (Entry-Level)',
 'Product/process development scientist',
 'Scientist, research (maths)',
 'Ecologist',
 'Materials engineer',
 'Historic buildings inspector/conservation officer',
 'Data scientist',
 'Psychiatrist',
 'Structural engineer',
 'Immigration officer',
 'Python Programmer (Entry-Level)',
 'Neurosurgeon',
 'Broadcast engineer',
 'Make',
 'Nurse, adult',
 'Air broker',
 'Editor, film/video',
 'Production assistant, radio',
 'Engineer, communications',
 'Sales executive',
 'Software Developer (Python)',
 'Futures trader',
 'Tour manager',
 'Cytogeneticist',
 'Designer, multimedia',
 'Trade union research officer',
 'Chemist, analytical',
 'Programmer, multimedia',
 'Engineer, broadcasting (operations)',
 'Teacher, primary school',
 'Python Developer',
 'Manufacturing systems engineer',
 'Producer, television/film/video',
 'Scientist, forensic',
 'Bonds trader',
 'Editorial assistant',
 'Photographer',
 'Retail banker',
 'Jewellery designer',
 'Ophthalmologist',
 'Back-End Web Developer (Python, Django)',
 'Licensed conveyancer',
 'Futures trader',
 'Counselling psychologist',
 'Insurance underwriter',
 'Engineer, automotive',
 'Producer, radio',
 'Dispensing optician',
 'Designer, fashion/clothing',
 'Chartered loss adjuster',
 'Back-End Web Developer (Python, Django)',
 'Forest/woodland manager',
 'Clinical cytogeneticist',
 'Print production planner',
 'Systems developer',
 'Graphic designer',
 'Writer',
 'Field seismologist',
 'Chief Strategy Officer',
 'Air cabin crew',
 'Python Programmer (Entry-Level)',
 'Warden/ranger',
 'Sports therapist',
 'Arts development officer',
 'Printmaker',
 'Health and safety adviser',
 'Manufacturing systems engineer',
 'Programmer, applications',
 'Medical physicist',
 'Media planner',
 'Software Developer (Python)',
 'Surveyor, land/geomatics',
 'Legal executive',
 'Librarian, academic',
 'Barrister',
 'Museum/gallery exhibitions officer',
 'Radiographer, diagnostic',
 'Database administrator',
 'Furniture designer',
 'Ship broker']

### c. Finally, extract the companies, locations, and posting dates for each job. For example, the first job has a company of "Payne, Roberts and Davis", a location of "Stewartbury, AA", and a posting date of "2021-04-08". Ensure that the text that you extract is clean, meaning no extra spaces or other characters at the beginning or end.

In [16]:
companies = soup.find_all('h3')

In [17]:
companies_list = [x.text for x in companies]

In [18]:
companies_list

['Payne, Roberts and Davis',
 'Vasquez-Davidson',
 'Jackson, Chambers and Levy',
 'Savage-Bradley',
 'Ramirez Inc',
 'Rogers-Yates',
 'Kramer-Klein',
 'Meyers-Johnson',
 'Hughes-Williams',
 'Jones, Williams and Villa',
 'Garcia PLC',
 'Gregory and Sons',
 'Clark, Garcia and Sosa',
 'Bush PLC',
 'Salazar-Meyers',
 'Parker, Murphy and Brooks',
 'Cruz-Brown',
 'Macdonald-Ferguson',
 'Williams, Peterson and Rojas',
 'Smith and Sons',
 'Moss, Duncan and Allen',
 'Gomez-Carroll',
 'Manning, Welch and Herring',
 'Lee, Gutierrez and Brown',
 'Davis, Serrano and Cook',
 'Smith LLC',
 'Thomas Group',
 'Silva-King',
 'Pierce-Long',
 'Walker-Simpson',
 'Cooper and Sons',
 'Donovan, Gonzalez and Figueroa',
 'Morgan, Butler and Bennett',
 'Snyder-Lee',
 'Harris PLC',
 'Washington PLC',
 'Brown, Price and Campbell',
 'Mcgee PLC',
 'Dixon Inc',
 'Thompson, Sheppard and Ward',
 'Adams-Brewer',
 'Schneider-Brady',
 'Gonzales-Frank',
 'Smith-Wong',
 'Pierce-Herrera',
 'Aguilar, Rivera and Quinn',
 'Lowe, Barnes and Thomas',
 'Lewis, Gonzalez and Vasquez',
 'Taylor PLC',
 'Oliver, Jones and Ramirez',
 'Rivera and Sons',
 'Garcia PLC',
 'Johnson, Wells and Kramer',
 'Gonzalez LLC',
 'Morgan, White and Macdonald',
 'Robinson-Fitzpatrick',
 'Waters, Wilson and Hoover',
 'Hill LLC',
 'Li-Gregory',
 'Fisher, Ryan and Coleman',
 'Stewart-Alexander',
 'Abbott and Sons',
 'Bryant, Santana and Davenport',
 'Smith PLC',
 'Patterson-Singh',
 'Martinez-Berry',
 'May, Taylor and Fisher',
 'Bailey, Owen and Thompson',
 'Vasquez Ltd',
 'Leblanc LLC',
 'Jackson, Ali and Mckee',
 'Blankenship, Knight and Powell',
 'Patton, Haynes and Jones',
 'Wood Inc',
 'Collins Group',
 'Flores-Nelson',
 'Mitchell, Jones and Olson',
 'Howard Group',
 'Kramer-Edwards',
 'Berry-Houston',
 'Mathews Inc',
 'Riley-Johnson',
 'Spencer and Sons',
 'Camacho-Sanchez',
 'Oliver and Sons',
 'Eaton PLC',
 'Stanley-Frederick',
 'Bradley LLC',
 'Parker, Goodwin and Zavala',
 'Kim-Miles',
 'Moreno-Rodriguez',
 'Brown-Ortiz',
 'Hartman PLC',
 'Brooks Inc',
 'Washington-Castillo',
 'Nguyen, Yoder and Petty',
 'Holder LLC',
 'Yates-Ferguson',
 'Ortega-Lawrence',
 'Fuentes, Walls and Castro']

In [19]:
locations = soup.find_all('p', class_= 'location')

In [20]:
locations[0].text.strip()

'Stewartbury, AA'

In [21]:
locations_list = [x.text.strip() for x in locations]

In [22]:
locations_list

['Stewartbury, AA',
 'Christopherville, AA',
 'Port Ericaburgh, AA',
 'East Seanview, AP',
 'North Jamieview, AP',
 'Davidville, AP',
 'South Christopher, AE',
 'Port Jonathan, AE',
 'Osbornetown, AE',
 'Scotttown, AP',
 'Ericberg, AE',
 'Ramireztown, AE',
 'Figueroaview, AA',
 'Kelseystad, AA',
 'Williamsburgh, AE',
 'Mitchellburgh, AE',
 'West Jessicabury, AA',
 'Maloneshire, AE',
 'Johnsonton, AA',
 'South Davidtown, AP',
 'Port Sara, AE',
 'Marktown, AA',
 'Laurenland, AE',
 'Lauraton, AP',
 'South Tammyberg, AP',
 'North Brandonville, AP',
 'Port Robertfurt, AA',
 'Burnettbury, AE',
 'Herbertside, AA',
 'Christopherport, AP',
 'West Victor, AE',
 'Port Aaron, AP',
 'Loribury, AA',
 'Angelastad, AP',
 'Larrytown, AE',
 'West Colin, AP',
 'West Stephanie, AP',
 'Laurentown, AP',
 'Wrightberg, AP',
 'Alberttown, AE',
 'Brockburgh, AE',
 'North Jason, AE',
 'Arnoldhaven, AE',
 'Lake Destiny, AP',
 'South Timothyburgh, AP',
 'New Jimmyton, AE',
 'New Lucasbury, AP',
 'Port Cory, AE',
 'Gileston, AA',
 'Cindyshire, AA',
 'East Michaelfort, AA',
 'Joybury, AE',
 'Emmatown, AE',
 'Colehaven, AP',
 'Port Coryton, AE',
 'Amyborough, AA',
 'Reynoldsville, AA',
 'Port Billy, AP',
 'Adamburgh, AA',
 'Wilsonmouth, AA',
 'South Kimberly, AA',
 'Benjaminland, AP',
 'Zacharyport, AA',
 'Port Devonville, AE',
 'East Thomas, AE',
 'New Jeffrey, AP',
 'Davidside, AA',
 'Jamesville, AA',
 'New Kelly, AP',
 'Lake Antonio, AA',
 'New Elizabethside, AA',
 'Millsbury, AE',
 'Lloydton, AP',
 'Port Jeremy, AA',
 'New Elizabethtown, AA',
 'Charlesstad, AE',
 'Josephbury, AE',
 'Seanfurt, AA',
 'Williambury, AA',
 'South Jorgeside, AP',
 'Robertborough, AP',
 'South Saratown, AP',
 'Hullview, AA',
 'Philipland, AP',
 'North Patty, AE',
 'North Stephen, AE',
 'Stevensland, AP',
 'Reyesstad, AE',
 'Bellberg, AP',
 'North Johnland, AE',
 'Martinezburgh, AE',
 'Joshuatown, AE',
 'West Ericstad, AA',
 'Tuckertown, AE',
 'Perezton, AE',
 'Lake Abigail, AE',
 'Jacobshire, AP',
 'Port Susan, AE',
 'North Tiffany, AA',
 'Michelleville, AP']

In [23]:
posting_date = soup.find_all('time')

In [24]:
posting_date_list = [x.text for x in posting_date]

In [25]:
posting_date_list

['2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08']

In [26]:
len(posting_date_list)

100

In [27]:
len(locations_list)

100

### d. Take the lists that you have created and combine them into a pandas DataFrame.

In [29]:
import pandas as pd

In [30]:
job_data = {
    'job_title': job_titles_list,
    'company': companies_list,
    'location': locations_list,
    'posting_date': posting_date_list}

In [31]:
df = pd.DataFrame(job_data)

In [32]:
df.head()

,job_title,company,location,posting_date
0,Senior Python Developer,"Payne, Roberts and Davis","Stewartbury, AA",2021-04-08
1,Energy engineer,Vasquez-Davidson,"Christopherville, AA",2021-04-08
2,Legal executive,"Jackson, Chambers and Levy","Port Ericaburgh, AA",2021-04-08
3,Fitness centre manager,Savage-Bradley,"East Seanview, AP",2021-04-08
4,Product manager,Ramirez Inc,"North Jamieview, AP",2021-04-08

#### 2. Next, add a column that contains the url for the "Apply" button. Try this in two ways.
#### a. First, use the BeautifulSoup find_all method to extract the urls.

In [34]:
url_ = soup.find_all('a',attrs={'class':'card-footer-item'})

In [35]:
url_

[<a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/senior-python-developer-0.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/energy-engineer-1.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/legal-executive-2.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/fitness-centre-manager-3.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/product-manager-4.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/medical-technical-officer-5.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/physiological-scientist-6.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/textile-designer-7.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/television-floor-manager-8.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/waste-management-officer-9.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/software-engineer-python-10.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/interpreter-11.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/architect-12.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/meteorologist-13.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/audiological-scientist-14.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/english-as-a-second-language-teacher-15.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/surgeon-16.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/equities-trader-17.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/newspaper-journalist-18.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/materials-engineer-19.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/python-programmer-entry-level-20.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/product-process-development-scientist-21.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/scientist-research-maths-22.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/ecologist-23.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/materials-engineer-24.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/historic-buildings-inspector-conservation-officer-25.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/data-scientist-26.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/psychiatrist-27.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/structural-engineer-28.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/immigration-officer-29.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/python-programmer-entry-level-30.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/neurosurgeon-31.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/broadcast-engineer-32.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/make-33.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/nurse-adult-34.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/air-broker-35.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/editor-film-video-36.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/production-assistant-radio-37.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/engineer-communications-38.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/sales-executive-39.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/software-developer-python-40.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/futures-trader-41.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/tour-manager-42.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/cytogeneticist-43.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/designer-multimedia-44.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/trade-union-research-officer-45.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/chemist-analytical-46.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/programmer-multimedia-47.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/engineer-broadcasting-operations-48.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/teacher-primary-school-49.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/python-developer-50.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/manufacturing-systems-engineer-51.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/producer-television-film-video-52.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/scientist-forensic-53.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/bonds-trader-54.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/editorial-assistant-55.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/photographer-56.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/retail-banker-57.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/jewellery-designer-58.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/ophthalmologist-59.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/back-end-web-developer-python-django-60.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/licensed-conveyancer-61.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/futures-trader-62.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/counselling-psychologist-63.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/insurance-underwriter-64.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/engineer-automotive-65.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/producer-radio-66.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/dispensing-optician-67.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/designer-fashion-clothing-68.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/chartered-loss-adjuster-69.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/back-end-web-developer-python-django-70.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/forest-woodland-manager-71.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/clinical-cytogeneticist-72.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/print-production-planner-73.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/systems-developer-74.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/graphic-designer-75.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/writer-76.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/field-seismologist-77.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/chief-strategy-officer-78.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/air-cabin-crew-79.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/python-programmer-entry-level-80.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/warden-ranger-81.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/sports-therapist-82.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/arts-development-officer-83.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/printmaker-84.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/health-and-safety-adviser-85.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/manufacturing-systems-engineer-86.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/programmer-applications-87.html" target="_blank">Apply</a>,
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>,

In [58]:
url_all = soup.find_all('a')[1]['href']

In [44]:
findd = soup.find('footer').find_all('a')[1].get('href')
findd

'https://realpython.github.io/fake-jobs/jobs/senior-python-developer-0.html'

In [48]:
apply_url_footer = soup.find_all('footer')

In [86]:
url_list = [x.find_all('a')[1].get('href') for x in apply_url_footer]

In [88]:
url_list

['https://realpython.github.io/fake-jobs/jobs/senior-python-developer-0.html',
 'https://realpython.github.io/fake-jobs/jobs/energy-engineer-1.html',
 'https://realpython.github.io/fake-jobs/jobs/legal-executive-2.html',
 'https://realpython.github.io/fake-jobs/jobs/fitness-centre-manager-3.html',
 'https://realpython.github.io/fake-jobs/jobs/product-manager-4.html',
 'https://realpython.github.io/fake-jobs/jobs/medical-technical-officer-5.html',
 'https://realpython.github.io/fake-jobs/jobs/physiological-scientist-6.html',
 'https://realpython.github.io/fake-jobs/jobs/textile-designer-7.html',
 'https://realpython.github.io/fake-jobs/jobs/television-floor-manager-8.html',
 'https://realpython.github.io/fake-jobs/jobs/waste-management-officer-9.html',
 'https://realpython.github.io/fake-jobs/jobs/software-engineer-python-10.html',
 'https://realpython.github.io/fake-jobs/jobs/interpreter-11.html',
 'https://realpython.github.io/fake-jobs/jobs/architect-12.html',
 'https://realpython.github.io/fake-jobs/jobs/meteorologist-13.html',
 'https://realpython.github.io/fake-jobs/jobs/audiological-scientist-14.html',
 'https://realpython.github.io/fake-jobs/jobs/english-as-a-second-language-teacher-15.html',
 'https://realpython.github.io/fake-jobs/jobs/surgeon-16.html',
 'https://realpython.github.io/fake-jobs/jobs/equities-trader-17.html',
 'https://realpython.github.io/fake-jobs/jobs/newspaper-journalist-18.html',
 'https://realpython.github.io/fake-jobs/jobs/materials-engineer-19.html',
 'https://realpython.github.io/fake-jobs/jobs/python-programmer-entry-level-20.html',
 'https://realpython.github.io/fake-jobs/jobs/product-process-development-scientist-21.html',
 'https://realpython.github.io/fake-jobs/jobs/scientist-research-maths-22.html',
 'https://realpython.github.io/fake-jobs/jobs/ecologist-23.html',
 'https://realpython.github.io/fake-jobs/jobs/materials-engineer-24.html',
 'https://realpython.github.io/fake-jobs/jobs/historic-buildings-inspector-conservation-officer-25.html',
 'https://realpython.github.io/fake-jobs/jobs/data-scientist-26.html',
 'https://realpython.github.io/fake-jobs/jobs/psychiatrist-27.html',
 'https://realpython.github.io/fake-jobs/jobs/structural-engineer-28.html',
 'https://realpython.github.io/fake-jobs/jobs/immigration-officer-29.html',
 'https://realpython.github.io/fake-jobs/jobs/python-programmer-entry-level-30.html',
 'https://realpython.github.io/fake-jobs/jobs/neurosurgeon-31.html',
 'https://realpython.github.io/fake-jobs/jobs/broadcast-engineer-32.html',
 'https://realpython.github.io/fake-jobs/jobs/make-33.html',
 'https://realpython.github.io/fake-jobs/jobs/nurse-adult-34.html',
 'https://realpython.github.io/fake-jobs/jobs/air-broker-35.html',
 'https://realpython.github.io/fake-jobs/jobs/editor-film-video-36.html',
 'https://realpython.github.io/fake-jobs/jobs/production-assistant-radio-37.html',
 'https://realpython.github.io/fake-jobs/jobs/engineer-communications-38.html',
 'https://realpython.github.io/fake-jobs/jobs/sales-executive-39.html',
 'https://realpython.github.io/fake-jobs/jobs/software-developer-python-40.html',
 'https://realpython.github.io/fake-jobs/jobs/futures-trader-41.html',
 'https://realpython.github.io/fake-jobs/jobs/tour-manager-42.html',
 'https://realpython.github.io/fake-jobs/jobs/cytogeneticist-43.html',
 'https://realpython.github.io/fake-jobs/jobs/designer-multimedia-44.html',
 'https://realpython.github.io/fake-jobs/jobs/trade-union-research-officer-45.html',
 'https://realpython.github.io/fake-jobs/jobs/chemist-analytical-46.html',
 'https://realpython.github.io/fake-jobs/jobs/programmer-multimedia-47.html',
 'https://realpython.github.io/fake-jobs/jobs/engineer-broadcasting-operations-48.html',
 'https://realpython.github.io/fake-jobs/jobs/teacher-primary-school-49.html',
 'https://realpython.github.io/fake-jobs/jobs/python-developer-50.html',
 'https://realpython.github.io/fake-jobs/jobs/manufacturing-systems-engineer-51.html',
 'https://realpython.github.io/fake-jobs/jobs/producer-television-film-video-52.html',
 'https://realpython.github.io/fake-jobs/jobs/scientist-forensic-53.html',
 'https://realpython.github.io/fake-jobs/jobs/bonds-trader-54.html',
 'https://realpython.github.io/fake-jobs/jobs/editorial-assistant-55.html',
 'https://realpython.github.io/fake-jobs/jobs/photographer-56.html',
 'https://realpython.github.io/fake-jobs/jobs/retail-banker-57.html',
 'https://realpython.github.io/fake-jobs/jobs/jewellery-designer-58.html',
 'https://realpython.github.io/fake-jobs/jobs/ophthalmologist-59.html',
 'https://realpython.github.io/fake-jobs/jobs/back-end-web-developer-python-django-60.html',
 'https://realpython.github.io/fake-jobs/jobs/licensed-conveyancer-61.html',
 'https://realpython.github.io/fake-jobs/jobs/futures-trader-62.html',
 'https://realpython.github.io/fake-jobs/jobs/counselling-psychologist-63.html',
 'https://realpython.github.io/fake-jobs/jobs/insurance-underwriter-64.html',
 'https://realpython.github.io/fake-jobs/jobs/engineer-automotive-65.html',
 'https://realpython.github.io/fake-jobs/jobs/producer-radio-66.html',
 'https://realpython.github.io/fake-jobs/jobs/dispensing-optician-67.html',
 'https://realpython.github.io/fake-jobs/jobs/designer-fashion-clothing-68.html',
 'https://realpython.github.io/fake-jobs/jobs/chartered-loss-adjuster-69.html',
 'https://realpython.github.io/fake-jobs/jobs/back-end-web-developer-python-django-70.html',
 'https://realpython.github.io/fake-jobs/jobs/forest-woodland-manager-71.html',
 'https://realpython.github.io/fake-jobs/jobs/clinical-cytogeneticist-72.html',
 'https://realpython.github.io/fake-jobs/jobs/print-production-planner-73.html',
 'https://realpython.github.io/fake-jobs/jobs/systems-developer-74.html',
 'https://realpython.github.io/fake-jobs/jobs/graphic-designer-75.html',
 'https://realpython.github.io/fake-jobs/jobs/writer-76.html',
 'https://realpython.github.io/fake-jobs/jobs/field-seismologist-77.html',
 'https://realpython.github.io/fake-jobs/jobs/chief-strategy-officer-78.html',
 'https://realpython.github.io/fake-jobs/jobs/air-cabin-crew-79.html',
 'https://realpython.github.io/fake-jobs/jobs/python-programmer-entry-level-80.html',
 'https://realpython.github.io/fake-jobs/jobs/warden-ranger-81.html',
 'https://realpython.github.io/fake-jobs/jobs/sports-therapist-82.html',
 'https://realpython.github.io/fake-jobs/jobs/arts-development-officer-83.html',
 'https://realpython.github.io/fake-jobs/jobs/printmaker-84.html',
 'https://realpython.github.io/fake-jobs/jobs/health-and-safety-adviser-85.html',
 'https://realpython.github.io/fake-jobs/jobs/manufacturing-systems-engineer-86.html',
 'https://realpython.github.io/fake-jobs/jobs/programmer-applications-87.html',
 'https://realpython.github.io/fake-jobs/jobs/medical-physicist-88.html',
 'https://realpython.github.io/fake-jobs/jobs/media-planner-89.html',
 'https://realpython.github.io/fake-jobs/jobs/software-developer-python-90.html',
 'https://realpython.github.io/fake-jobs/jobs/surveyor-land-geomatics-91.html',
 'https://realpython.github.io/fake-jobs/jobs/legal-executive-92.html',
 'https://realpython.github.io/fake-jobs/jobs/librarian-academic-93.html',
 'https://realpython.github.io/fake-jobs/jobs/barrister-94.html',
 'https://realpython.github.io/fake-jobs/jobs/museum-gallery-exhibitions-officer-95.html',
 'https://realpython.github.io/fake-jobs/jobs/radiographer-diagnostic-96.html',
 'https://realpython.github.io/fake-jobs/jobs/database-administrator-97.html',
 'https://realpython.github.io/fake-jobs/jobs/furniture-designer-98.html',
 'https://realpython.github.io/fake-jobs/jobs/ship-broker-99.html']

In [60]:
df['url'] = apply_url

In [62]:
df.head()

,job_title,company,location,posting_date,url
0,Senior Python Developer,"Payne, Roberts and Davis","Stewartbury, AA",2021-04-08,https://realpython.github.io/fake-jobs/jobs/se...
1,Energy engineer,Vasquez-Davidson,"Christopherville, AA",2021-04-08,https://realpython.github.io/fake-jobs/jobs/en...
2,Legal executive,"Jackson, Chambers and Levy","Port Ericaburgh, AA",2021-04-08,https://realpython.github.io/fake-jobs/jobs/le...
3,Fitness centre manager,Savage-Bradley,"East Seanview, AP",2021-04-08,https://realpython.github.io/fake-jobs/jobs/fi...
4,Product manager,Ramirez Inc,"North Jamieview, AP",2021-04-08,https://realpython.github.io/fake-jobs/jobs/pr...

### b. Next, get those same urls in a different way. Examine the urls and see if you can spot the pattern of how they are constructed. Then, build the url using the elements you have already extracted. Ensure that the urls that you created match those that you extracted using BeautifulSoup. Warning: You will need to do some string cleaning and prep in constructing the urls this way. For example, look carefully at the urls for the "Software Engineer (Python)" job and the "Scientist, research (maths)" job.

In [98]:
url_prefix = 'https://realpython.github.io/fake_jobs/jobs/'
url_suffix ='.html'
other_url_list = []

for i, t in enumerate(job_titles_list):
       clean_url = print(f"{url_prefix}{t.lower().replace(' ', '-').replace('(',' ').replace(')',' ').replace(',','').replace('/','-').replace(' ','')}-{i}{url_suffix}")
       other_url_list.append(clean_url)

https://realpython.github.io/fake_jobs/jobs/senior-python-developer-0.html
https://realpython.github.io/fake_jobs/jobs/energy-engineer-1.html
https://realpython.github.io/fake_jobs/jobs/legal-executive-2.html
https://realpython.github.io/fake_jobs/jobs/fitness-centre-manager-3.html
https://realpython.github.io/fake_jobs/jobs/product-manager-4.html
https://realpython.github.io/fake_jobs/jobs/medical-technical-officer-5.html
https://realpython.github.io/fake_jobs/jobs/physiological-scientist-6.html
https://realpython.github.io/fake_jobs/jobs/textile-designer-7.html
https://realpython.github.io/fake_jobs/jobs/television-floor-manager-8.html
https://realpython.github.io/fake_jobs/jobs/waste-management-officer-9.html
https://realpython.github.io/fake_jobs/jobs/software-engineer-python-10.html
https://realpython.github.io/fake_jobs/jobs/interpreter-11.html
https://realpython.github.io/fake_jobs/jobs/architect-12.html
https://realpython.github.io/fake_jobs/jobs/meteorologist-13.html
https://realpython.github.io/fake_jobs/jobs/audiological-scientist-14.html
https://realpython.github.io/fake_jobs/jobs/english-as-a-second-language-teacher-15.html
https://realpython.github.io/fake_jobs/jobs/surgeon-16.html
https://realpython.github.io/fake_jobs/jobs/equities-trader-17.html
https://realpython.github.io/fake_jobs/jobs/newspaper-journalist-18.html
https://realpython.github.io/fake_jobs/jobs/materials-engineer-19.html
https://realpython.github.io/fake_jobs/jobs/python-programmer-entry-level-20.html
https://realpython.github.io/fake_jobs/jobs/product-process-development-scientist-21.html
https://realpython.github.io/fake_jobs/jobs/scientist-research-maths-22.html
https://realpython.github.io/fake_jobs/jobs/ecologist-23.html
https://realpython.github.io/fake_jobs/jobs/materials-engineer-24.html
https://realpython.github.io/fake_jobs/jobs/historic-buildings-inspector-conservation-officer-25.html
https://realpython.github.io/fake_jobs/jobs/data-scientist-26.html
https://realpython.github.io/fake_jobs/jobs/psychiatrist-27.html
https://realpython.github.io/fake_jobs/jobs/structural-engineer-28.html
https://realpython.github.io/fake_jobs/jobs/immigration-officer-29.html
https://realpython.github.io/fake_jobs/jobs/python-programmer-entry-level-30.html
https://realpython.github.io/fake_jobs/jobs/neurosurgeon-31.html
https://realpython.github.io/fake_jobs/jobs/broadcast-engineer-32.html
https://realpython.github.io/fake_jobs/jobs/make-33.html
https://realpython.github.io/fake_jobs/jobs/nurse-adult-34.html
https://realpython.github.io/fake_jobs/jobs/air-broker-35.html
https://realpython.github.io/fake_jobs/jobs/editor-film-video-36.html
https://realpython.github.io/fake_jobs/jobs/production-assistant-radio-37.html
https://realpython.github.io/fake_jobs/jobs/engineer-communications-38.html
https://realpython.github.io/fake_jobs/jobs/sales-executive-39.html
https://realpython.github.io/fake_jobs/jobs/software-developer-python-40.html
https://realpython.github.io/fake_jobs/jobs/futures-trader-41.html
https://realpython.github.io/fake_jobs/jobs/tour-manager-42.html
https://realpython.github.io/fake_jobs/jobs/cytogeneticist-43.html
https://realpython.github.io/fake_jobs/jobs/designer-multimedia-44.html
https://realpython.github.io/fake_jobs/jobs/trade-union-research-officer-45.html
https://realpython.github.io/fake_jobs/jobs/chemist-analytical-46.html
https://realpython.github.io/fake_jobs/jobs/programmer-multimedia-47.html
https://realpython.github.io/fake_jobs/jobs/engineer-broadcasting-operations-48.html
https://realpython.github.io/fake_jobs/jobs/teacher-primary-school-49.html
https://realpython.github.io/fake_jobs/jobs/python-developer-50.html
https://realpython.github.io/fake_jobs/jobs/manufacturing-systems-engineer-51.html
https://realpython.github.io/fake_jobs/jobs/producer-television-film-video-52.html
https://realpython.github.io/fake_jobs/jobs/scientist-forensic-53.html
https://realpython.github.io/fake_jobs/jobs/bonds-trader-54.html
https://realpython.github.io/fake_jobs/jobs/editorial-assistant-55.html
https://realpython.github.io/fake_jobs/jobs/photographer-56.html
https://realpython.github.io/fake_jobs/jobs/retail-banker-57.html
https://realpython.github.io/fake_jobs/jobs/jewellery-designer-58.html
https://realpython.github.io/fake_jobs/jobs/ophthalmologist-59.html
https://realpython.github.io/fake_jobs/jobs/back-end-web-developer-python-django-60.html
https://realpython.github.io/fake_jobs/jobs/licensed-conveyancer-61.html
https://realpython.github.io/fake_jobs/jobs/futures-trader-62.html
https://realpython.github.io/fake_jobs/jobs/counselling-psychologist-63.html
https://realpython.github.io/fake_jobs/jobs/insurance-underwriter-64.html
https://realpython.github.io/fake_jobs/jobs/engineer-automotive-65.html
https://realpython.github.io/fake_jobs/jobs/producer-radio-66.html
https://realpython.github.io/fake_jobs/jobs/dispensing-optician-67.html
https://realpython.github.io/fake_jobs/jobs/designer-fashion-clothing-68.html
https://realpython.github.io/fake_jobs/jobs/chartered-loss-adjuster-69.html
https://realpython.github.io/fake_jobs/jobs/back-end-web-developer-python-django-70.html
https://realpython.github.io/fake_jobs/jobs/forest-woodland-manager-71.html
https://realpython.github.io/fake_jobs/jobs/clinical-cytogeneticist-72.html
https://realpython.github.io/fake_jobs/jobs/print-production-planner-73.html
https://realpython.github.io/fake_jobs/jobs/systems-developer-74.html
https://realpython.github.io/fake_jobs/jobs/graphic-designer-75.html
https://realpython.github.io/fake_jobs/jobs/writer-76.html
https://realpython.github.io/fake_jobs/jobs/field-seismologist-77.html
https://realpython.github.io/fake_jobs/jobs/chief-strategy-officer-78.html
https://realpython.github.io/fake_jobs/jobs/air-cabin-crew-79.html
https://realpython.github.io/fake_jobs/jobs/python-programmer-entry-level-80.html
https://realpython.github.io/fake_jobs/jobs/warden-ranger-81.html
https://realpython.github.io/fake_jobs/jobs/sports-therapist-82.html
https://realpython.github.io/fake_jobs/jobs/arts-development-officer-83.html
https://realpython.github.io/fake_jobs/jobs/printmaker-84.html
https://realpython.github.io/fake_jobs/jobs/health-and-safety-adviser-85.html
https://realpython.github.io/fake_jobs/jobs/manufacturing-systems-engineer-86.html
https://realpython.github.io/fake_jobs/jobs/programmer-applications-87.html
https://realpython.github.io/fake_jobs/jobs/medical-physicist-88.html
https://realpython.github.io/fake_jobs/jobs/media-planner-89.html
https://realpython.github.io/fake_jobs/jobs/software-developer-python-90.html
https://realpython.github.io/fake_jobs/jobs/surveyor-land-geomatics-91.html
https://realpython.github.io/fake_jobs/jobs/legal-executive-92.html
https://realpython.github.io/fake_jobs/jobs/librarian-academic-93.html
https://realpython.github.io/fake_jobs/jobs/barrister-94.html
https://realpython.github.io/fake_jobs/jobs/museum-gallery-exhibitions-officer-95.html
https://realpython.github.io/fake_jobs/jobs/radiographer-diagnostic-96.html
https://realpython.github.io/fake_jobs/jobs/database-administrator-97.html
https://realpython.github.io/fake_jobs/jobs/furniture-designer-98.html
https://realpython.github.io/fake_jobs/jobs/ship-broker-99.html

In [100]:
df['url_other'] = other_url_list

In [102]:
df.head()

,job_title,company,location,posting_date,url,description,url_other
0,Senior Python Developer,"Payne, Roberts and Davis","Stewartbury, AA",2021-04-08,https://realpython.github.io/fake-jobs/jobs/se...,Professional asset web application environment...,None
1,Energy engineer,Vasquez-Davidson,"Christopherville, AA",2021-04-08,https://realpython.github.io/fake-jobs/jobs/en...,Party prevent live. Quickly candidate change a...,None
2,Legal executive,"Jackson, Chambers and Levy","Port Ericaburgh, AA",2021-04-08,https://realpython.github.io/fake-jobs/jobs/le...,Administration even relate head color. Staff b...,None
3,Fitness centre manager,Savage-Bradley,"East Seanview, AP",2021-04-08,https://realpython.github.io/fake-jobs/jobs/fi...,Tv program actually race tonight themselves tr...,None
4,Product manager,Ramirez Inc,"North Jamieview, AP",2021-04-08,https://realpython.github.io/fake-jobs/jobs/pr...,Traditional page a although for study anyone. ...,None

### 3. Finally, we want to get the job description text for each job.  
 ### a. Start by looking at the page for the first job,

In [70]:
url2 = 'https://realpython.github.io/fake-jobs/jobs/senior-python-developer-0.html'

r = requests.get(url2)
soup = BS(r.text)

In [104]:
soup.find('div', class_='content').find('p').text

'Professional asset web application environmentally friendly detail-oriented asset. Coordinate educational dashboard agile employ growth opportunity. Company programs CSS explore role. Html educational grit web application. Oversea SCRUM talented support. Web Application fast-growing communities inclusive programs job CSS. Css discussions growth opportunity explore open-minded oversee. Css Python environmentally friendly collaborate inclusive role. Django no experience oversee dashboard environmentally friendly willing to learn programs. Programs open-minded programs asset.'

### b. We want to be able to do this for all pages. Write a function which takes as input a url and returns the description text on that page. For example, if you input "https://realpython.github.io/fake-jobs/jobs/television-floor-manager-8.html" into your function, it should return the string "At be than always different American address. Former claim chance prevent why measure too. Almost before some military outside baby interview. Face top individual win suddenly. Parent do ten after those scientist. Medical effort assume teacher wall. Significant his himself clearly very. Expert stop area along individual. Three own bank recognize special good along.".

In [108]:
def get_description(url):
    r = requests.get(url)
    soup = BS(r.text)
    return soup.find('div', class_='content').find('p').text
   
get_description(url_list[7])

'Court boy state table agree moment. Budget huge debate among way. Perhaps bit learn gun still. Writer work chance image. There many true follow marriage material. Myself use act relationship section.'

### c. Use the [.apply method](https://pandas.pydata.org/docs/reference/api/pandas.Series.apply.html) on the url column you created above to retrieve the description text for all of the jobs.

In [92]:
df['description'] = df['url'].apply(get_description)

In [94]:
df.head()

,job_title,company,location,posting_date,url,description
0,Senior Python Developer,"Payne, Roberts and Davis","Stewartbury, AA",2021-04-08,https://realpython.github.io/fake-jobs/jobs/se...,Professional asset web application environment...
1,Energy engineer,Vasquez-Davidson,"Christopherville, AA",2021-04-08,https://realpython.github.io/fake-jobs/jobs/en...,Party prevent live. Quickly candidate change a...
2,Legal executive,"Jackson, Chambers and Levy","Port Ericaburgh, AA",2021-04-08,https://realpython.github.io/fake-jobs/jobs/le...,Administration even relate head color. Staff b...
3,Fitness centre manager,Savage-Bradley,"East Seanview, AP",2021-04-08,https://realpython.github.io/fake-jobs/jobs/fi...,Tv program actually race tonight themselves tr...
4,Product manager,Ramirez Inc,"North Jamieview, AP",2021-04-08,https://realpython.github.io/fake-jobs/jobs/pr...,Traditional page a although for study anyone. ...